export const POKEMON_TYPES = [
    { name: "bug", color: "#7bcf00", icon: "material-symbols:bug-report-outline" },
    { name: "dark", color: "#5a566a", icon: "material-symbols-light:dark-mode-outline" },
    { name: "dragon", color: "#0076ff", icon: "la:dragon" },
    { name: "electric", color: "#ffde00", icon: "material-symbols-light:electric-bolt-outline" },
    { name: "fairy", color: "#ff76ff", icon: "game-icons:fairy-wings" },
    { name: "fighting", color: "#ff215b", icon: "ph:hand-fist-light" },
    { name: "fire", color: "#ff9900", icon: "simple-line-icons:fire" },
    { name: "flying", color: "#89bdff", icon: "ph:cloud" },
    { name: "ghost", color: "#4e6aff", icon: "ph:ghost" },
    { name: "grass", color: "#1cd80e", icon: "game-icons:grass" },
    { name: "ground", color: "#ff6b0d", icon: "tabler:circuit-ground" },
    { name: "ice", color: "#2ee4c6", icon: "streamline:interface-weather-snow-flake-winter-freeze-snow-freezing-ice-cold-weather-snowflake" },
    { name: "normal", color: "#9fa39d", icon: "mdi:origin" },
    { name: "poison", color: "#f149ff", icon: "game-icons:poison" },
    { name: "psychic", color: "#ff6c64", icon: "material-symbols:psychiatry-outline" },
    { name: "rock", color: "#d8bc5a", icon: "game-icons:stone-sphere" },
    { name: "steel", color: "#23a1bd", icon: "game-icons:steel-claws" },
    { name: "water", color: "#14a8ff", icon: "ion:water-outline" },
  ];